final_space: true
version: 2
blocks:
  - type: prompt # first line left
    alignment: left
    segments:
      - type: shell # shell segment
        style: powerline
        invert_powerline: true
        powerline_symbol: "\u256d"
        background: "#00d9ff"
        foreground: "#000000"
        properties:
          mapped_shell_names:
            bash: "󱆃 bash"
            pwsh: "󰨊 PS"
        template: " {{.Name}} "
      - type : root # root segment
        style: diamond
        background: "#ffd000"
        foreground: "#ff0000"
        template: "<parentBackground>\ue0b0</> 󰌋 "
      - type: session # session segment
        style: powerline
        powerline_symbol: "\ue0b0"
        background: "#a70000"
        foreground: "#ffffff"
        template: "{{if .Root}} \ue691 {{.UserName}}@{{ .HostName }} {{else}}  {{.UserName}}@{{ .HostName }} {{end}}"
      - type: path # path segment (Non Root)
        style: powerline
        powerline_symbol: "\ue0b0"
        background: "#FF9248"
        foreground: "#000000"
        properties:
          exclude_folders:
            - C:/
            - /
          style: agnoster
          home_icon: "\uf015"
          folder_icon: "\ue5ff"
          folder_separator_icon: " \ue0bb "
        template: " \uf07b\uea9c {{ .Path }} "
      - type: path # path segment (Root)
        style: powerline
        powerline_symbol: "\ue0b0"
        background: "#FF9248"
        foreground: "#000000"
        properties:
          include_folders:
            - C:/
            - /
          style: agnoster
          home_icon: "\uf015"
          folder_icon: "\ue5ff"
          folder_separator_icon: " "
        template: " 󰋊\uea9c {{ .Path }}"
      - type: git
        background: "#FFFB38"
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}"
          - "{{ if gt .Ahead 0 }}#C792EA{{ end }}"
          - "{{ if gt .Behind 0 }}#C792EA{{ end }}"
        foreground: "#011627"
        powerline_symbol: "\ue0b0"
        properties:
          branch_icon: "\ue725 "
          fetch_status: true
          fetch_upstream_icon: true
        style: powerline
        template: " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} "



  - type: prompt
    alignment: right
    segments:
      - type: node
        style: diamond
        background: "#303030"
        foreground: "#3C873A"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          fetch_package_manager: true
          npm_icon: " <#cc3a3a>\ue5fa</> "
          yarn_icon: " <#348cba>\ue6a7</>"
        template: "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
      - type: python
        style: diamond
        background: "#306998"
        foreground: "#FFE873"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
      - type: java
        style: diamond
        background: "#0e8ac8"
        foreground: "#ffffff"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: dotnet
        style: diamond
        background: "#0e0e0e"
        foreground: "#0d6da8"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue77f {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }}"
      - type: go
        style: diamond
        background: "#ffffff"
        foreground: "#06aad5"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: rust
        style: diamond
        background: "#f3f0ec"
        foreground: "#925837"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: dart
        style: diamond
        background: "#e1e8e9"
        foreground: "#055b9c"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: angular
        style: diamond
        background: "#ffffff"
        foreground: "#ce092f"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: nx
        style: diamond
        background: "#1e293b"
        foreground: "#ffffff"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}"
      - type: julia
        style: diamond
        background: "#945bb3"
        foreground: "#359a25"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "<#ca3c34>\ue624</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: ruby
        style: diamond
        background: "#ffffff"
        foreground: "#9c1006"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: azfunc
        style: diamond
        background: "#ffffff"
        foreground: "#5398c2"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\uf104<#f5bf45>\uf0e7</>\uf105 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
      - type: aws
        style: diamond
        background: "#565656"
        foreground: "#faa029"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\ue7ad {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
      - type: kubectl
        style: diamond
        background: "#316ce4"
        foreground: "#ffffff"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        template: "\uf308 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
      - type: os
        style: diamond
        background: "#636363"
        foreground: "#f3f3f3"
        leading_diamond: "\ue0b6"
        properties:
          linux: "\uf303"
          macos: "\ue711"
          windows: "\ue70f"
        template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
      - type: connection
        style: powerline
        invert_powerline: true
        background: "#1fb4be"
        foreground: "#222222"
        powerline_symbol: "\ue0b2"
        template: "{{if eq .Type \"ethernet\"}} 󰈁 {{else if eq .Type \"wifi\"}} 󰖩 {{else}} 󰲜 {{end}}"
      - type: battery
        style: powerline
        invert_powerline: true
        background: "#f36943"
        background_templates:
          - "{{if eq \"Charging\" .State.String}}#b8e994{{end}}"
          - "{{if eq \"Discharging\" .State.String}}#fff34e{{end}}"
          - "{{if eq \"Full\" .State.String}}#33DD2D{{end}}"
          - "{{ if gt .Percentage 25 }}#f44336{{ end }}"
        foreground: "#262626"
        powerline_symbol: "\ue0b2"
        properties:
          charged_icon: "󰁹 "
          discharging_icon: "󰁾 "
          charging_icon: " "
          not_charging_icon: "󰂃 "
        template: " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 "
      - type: executiontime
        style: diamond
        invert_powerline: true
        background: "#83769c"
        foreground: "#ffffff"
        trailing_diamond: "\ue0bc"
        properties:
          style: roundrock
          threshold: 0
        template: " \ueba2 {{ .FormattedMs }}\u2800"
      - type: time
        style: diamond
        invert_powerline: true
        background: "#0077c2"
        foreground: "#ffffff"
        trailing_diamond: "\ue0b4"
        properties:
          time_format: "15:04:05"
        template: " \uf43a {{ .CurrentDate | date .Format }} "


  - type: prompt
    alignment: left
    newline: true
    segments:
      - foreground: "#00d9ff" # cmd leading lines vertical
        style: plain
        template: "\u2502"
        type: text
      - type: sysinfo
        leading_diamond: " "
        trailing_diamond: " "
        foreground: "#ffffff"
        background: "#8f43f3"
        template: "  {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB) "
        properties:
          precision: 2
        style: diamond
      - type: upgrade
        style: diamond
        foreground: "#111111"
        background: "#FFD664"
        leading_diamond: ""
        trailing_diamond: " "
        template: " 󱆃 {{ .Current }} "



  - type: prompt
    alignment: right
    segments:
      - type: status
        style: diamond
        foreground: "#ffffff"
        background: "#00b536"
        background_templates:
          - "{{ if .Error }}#ff0000{{ end }}"
        leading_diamond: ""
        template: "{{if .Error}}  {{else}}  {{end}}"
        properties:
          always_enabled: true
      - type: ipify
        style: diamond
        foreground: "#ffffff"
        background: "#c386f1"
        leading_diamond: ""
        trailing_diamond: " "
        template: " 󱦂 {{ .IP }}"
        properties:
          cache_timeout: 5
          http_timeout: 1000



  - type: prompt
    alignment: left
    newline: true
    segments:
      - foreground: "#00d9ff" # cmd leading lines
        style: plain
        template: "\u2570\u2500"
        type: text
      - foreground: "#e0f8ff" # prompt
        style: plain
        template: "\ue602\ueab6"
        type: status
        properties:
          always_enabled: true
